# Generated by Django 5.2.7 on 2025-12-22 15:47

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50, unique=True)),
                ('Category_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Brand', models.CharField(blank=True, max_length=50, null=True)),
                ('Color', models.CharField(blank=True, max_length=50, null=True)),
                ('Model_No', models.CharField(max_length=50, unique=True)),
                ('Size', models.CharField()),
                ('Material', models.CharField(max_length=50)),
                ('Finish', models.CharField(max_length=50, null=True)),
                ('Price', models.FloatField(blank=True, max_length=10, null=True)),
                ('Thickness', models.CharField(blank=True, max_length=10, null=True)),
                ('Description', models.TextField(blank=True, max_length=100)),
                ('slug', models.SlugField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
