# Generated by Django 5.2.7 on 2025-11-28 13:56

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_galleryalbum_remove_galleryimage_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Finish',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(blank=True, upload_to='static/media/category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Model_No',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='static/media/product'),
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hardware_Image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='static/media/hardware')),
                ('Finish', models.CharField(max_length=50)),
                ('Material', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('Model_NO', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardwares',
            },
        ),
    ]
