# Generated by Django 5.2.7 on 2025-11-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_description_products_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Size',
            field=models.CharField(),
        ),
    ]
