# Generated by Django 5.2.7 on 2025-11-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='Price',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
