# Generated by Django 5.2.7 on 2025-12-05 15:11

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_hardware_price_alter_products_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='Model_NO',
            new_name='Model_No',
        ),
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_Image',
            field=models.ImageField(upload_to='static/media/category'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=90, scale=None, size=[1920, 1080], upload_to='gallery_images'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='Hardware_Image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='static/media/hardware'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='static/media/product'),
        ),
    ]
