# Generated by Django 5.2.7 on 2025-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_model_no_hardware_model_no_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Thickness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Hardware',
        ),
    ]
