# Generated by Django 5.2.7 on 2025-12-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
