# Generated by Django 5.2.7 on 2025-12-19 14:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='image_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Product_Image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
